version: '3.8'

services:
  stashhsp:
    image: ghcr.io/nodudewastaken/stash-hsp:latest
    container_name: stash_hsp
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "3000:3000"  # Adjust port as needed
    environment:
      PORT: 3000 # The port stash_hsp runs on
      STASH_URL: "http://192.168.1.123:9999" # Stash's URL
      STASH_APIKEY: abcd # Stash api key if needed
      DATA_DIR: "/data"
      SCALE_PROCESS_LIMIT: 8 # When downscaling screenshots, how many concurrent processes are allowed
      SCANCACHE_CRON: "0 6 * * *" # How often to regenerate the scan database of all scenes
      LOCALHSP: "" # Set to a directory like ./data/hspfiles if we dont have access to stash, so we store HSP files locally instead of assuming direct access
    volumes:
      - logs-storage:/logs
      - ./data:/data

volumes:
  screenshot-storage: {}
  cache-storage: {}
  logs-storage: {}
