version: '3.8'

services:
  stashhsp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stash_hsp
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "3000:3000"  # Adjust port as needed
    environment:
      STASH_URL: "http://192.168.1.123:9999"
      PORT: 3000
      SCREENSHOTS_DIR: "/screenshots"
      VAR_CACHE_DIR: "/cache"
      SCALE_PROCESS_LIMIT: 8
      REQUEST_PROCESS_LIMIT: 20
    volumes:
      - screenshot-storage:/screenshots
      - cache-storage:/cache
    healthcheck:
      test: curl --fail http://localhost:3000/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

volumes:
  screenshot-storage: {}
  cache-storage: {}
