version: '3.8'

services:
  stashhsp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stash_hsp
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "3000:3000"  # Adjust port as needed
    environment:
      STASH_URL: "http://192.168.1.123:9999"
      SERVICE_IP: "0.0.0.0"
      PORT: 3000
      SCREENSHOTS_DIR: "/screenshots"
    volumes:
      - screenshot-storage:/screenshots

volumes:
  screenshot-storage: {}
