version: '3.8'

services:
  stashhsp:
    image: ghcr.io/nodudewastaken/stash-hsp:latest
    container_name: stash_hsp
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "3000:3000"  # Adjust port as needed
    environment:
      PORT: 3000 # The port stash_hsp runs on
      STASH_URL: "http://192.168.1.123:9999" # Stash's URL
      STASH_APIKEY: abcd # Stash api key if needed
      SCREENSHOTS_DIR: "/screenshots"
      CACHE_DIR: "/cache"
      SCALE_PROCESS_LIMIT: 8 # When downscaling screenshots, how many concurrent processes are allowed
      REQUEST_PROCESS_LIMIT: 20 # When fetching scenes from stash, how many concurrent requests
      SCANCACHE_CRON: "0 6 * * *" # How often to regenerate the scan database of all scenes
      VAR_LOCALHSP: "" # Set to a directory like /hspfiles if we dont have access to stash, so we store HSP files locally instead of assuming direct access
    volumes:
      - screenshot-storage:/screenshots
      - cache-storage:/cache
    healthcheck:
      test: curl --fail http://localhost:3000/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

volumes:
  screenshot-storage: {}
  cache-storage: {}
